-- CRM notice board for login screen and sidebar notice popup.
-- Run this in the Supabase SQL Editor.

create table if not exists public.crm_notices (
  id bigint generated by default as identity primary key,
  title text not null default '공지사항',
  content text not null,
  image_path text not null default '',
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.crm_notices
  add column if not exists image_path text not null default '';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'crm-notice-images',
  'crm-notice-images',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.crm_notices enable row level security;

grant select on public.crm_notices to anon, authenticated;
grant insert, update on public.crm_notices to authenticated;
grant usage, select on sequence public.crm_notices_id_seq to authenticated;

drop policy if exists crm_notices_public_select on public.crm_notices;
create policy crm_notices_public_select on public.crm_notices
  for select
  using (is_active = true);

drop policy if exists crm_notices_admin_insert on public.crm_notices;
create policy crm_notices_admin_insert on public.crm_notices
  for insert
  with check (public.current_profile_is_privileged());

drop policy if exists crm_notices_admin_update on public.crm_notices;
create policy crm_notices_admin_update on public.crm_notices
  for update
  using (public.current_profile_is_privileged())
  with check (public.current_profile_is_privileged());

create index if not exists crm_notices_active_created_at_idx
  on public.crm_notices(is_active, created_at desc);

drop policy if exists crm_notice_images_authenticated_select on storage.objects;
create policy crm_notice_images_authenticated_select on storage.objects
for select
to authenticated
using (bucket_id = 'crm-notice-images');

drop policy if exists crm_notice_images_admin_insert on storage.objects;
create policy crm_notice_images_admin_insert on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'crm-notice-images'
  and public.current_profile_is_privileged()
);

drop policy if exists crm_notice_images_admin_update on storage.objects;
create policy crm_notice_images_admin_update on storage.objects
for update
to authenticated
using (
  bucket_id = 'crm-notice-images'
  and public.current_profile_is_privileged()
)
with check (
  bucket_id = 'crm-notice-images'
  and public.current_profile_is_privileged()
);

drop policy if exists crm_notice_images_admin_delete on storage.objects;
create policy crm_notice_images_admin_delete on storage.objects
for delete
to authenticated
using (
  bucket_id = 'crm-notice-images'
  and public.current_profile_is_privileged()
);
