-- CRM notice board for login screen and sidebar notice popup.
-- Run this in the Supabase SQL Editor.

create table if not exists public.crm_notices (
  id bigint generated by default as identity primary key,
  title text not null default '공지사항',
  content text not null,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.crm_notices enable row level security;

grant select on public.crm_notices to anon, authenticated;
grant insert, update on public.crm_notices to authenticated;
grant usage, select on sequence public.crm_notices_id_seq to authenticated;

drop policy if exists crm_notices_public_select on public.crm_notices;
create policy crm_notices_public_select on public.crm_notices
  for select
  using (is_active = true);

drop policy if exists crm_notices_admin_insert on public.crm_notices;
create policy crm_notices_admin_insert on public.crm_notices
  for insert
  with check (public.current_profile_is_privileged());

drop policy if exists crm_notices_admin_update on public.crm_notices;
create policy crm_notices_admin_update on public.crm_notices
  for update
  using (public.current_profile_is_privileged())
  with check (public.current_profile_is_privileged());

create index if not exists crm_notices_active_created_at_idx
  on public.crm_notices(is_active, created_at desc);
